strani = ['bangladesh', 'usa', 'russia', 'kanada', 'england', 'germany']
print('Страны, в которых я бы хотел побывать:')
print(strani)

print('Отсортированный в алфавитном порядке список:')
print(sorted(strani))
print('Исходный список:')
print(strani)
print('Вывод списка в обратном алфавитном порядке:')
print(sorted(strani, reverse=True))
print('Исходный список:')
print(strani)
strani.reverse()
print('Вывод списка в обратном порядке:')
print(strani)
strani.reverse()
print('Вернули список к первоначальному состоянию:')
print(strani)
strani.sort()
print('Навсегда отсортировали список в алфавитном порядке:')
print(strani)
strani.sort(reverse=True)
print('Навсегда отсортировали список в обратном алфавитном порядке:')
print(strani)
